export const CREATE_CLASSROOM_REQUEST = 'CREATE_CLASSROOM_REQUEST';
export const CREATE_CLASSROOM_SUCCESS = 'CREATE_CLASSROOM_SUCCESS';
export const CREATE_CLASSROOM_FAILURE = 'CREATE_CLASSROOM_FAILURE';
