export const DELETE_CLASSROOM_REQUEST = 'DELETE_CLASSROOM_REQUEST';
export const DELETE_CLASSROOM_SUCCESS = 'DELETE_CLASSROOM_SUCCESS';
export const DELETE_CLASSROOM_FAILURE = 'DELETE_CLASSROOM_FAILURE';
