export const UPDATE_CLASSROOM_REQUEST = 'UPDATE_CLASSROOM_REQUEST';
export const UPDATE_CLASSROOM_SUCCESS = 'UPDATE_CLASSROOM_SUCCESS';
export const UPDATE_CLASSROOM_FAILURE = 'UPDATE_CLASSROOM_FAILURE';
