export const CREATE_LECTURE_REGISTER_REQUEST =
  'CREATE_LECTURE_REGISTER_REQUEST';
export const CREATE_LECTURE_REGISTER_SUCCESS =
  'CREATE_LECTURE_REGISTER_SUCCESS';
export const CREATE_LECTURE_REGISTER_FAILURE =
  'CREATE_LECTURE_REGISTER_FAILURE';
