export const FETCH_LECTURE_REGISTER_REQUEST = 'FETCH_LECTURE_REGISTER_REQUEST';
export const FETCH_LECTURE_REGISTER_SUCCESS = 'FETCH_LECTURE_REGISTER_SUCCESS';
export const FETCH_LECTURE_REGISTER_FAILURE = 'FETCH_LECTURE_REGISTER_FAILURE';
